# Generated by Django 5.2 on 2025-04-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_images', '0002_alter_customimage_api_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customimage',
            name='api_upload',
            field=models.BooleanField(default=False),
        ),
    ]
