# Generated by Django 5.2 on 2025-04-11 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_images', '0005_rename_hidden_customimage_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customimage',
            name='public',
        ),
    ]
