# Generated by Django 5.2 on 2025-04-04 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custom_images", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customimage",
            name="api_upload",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
