# Generated by Django 5.2 on 2025-04-07 08:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("custom_images", "0003_alter_customimage_api_upload"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customimage",
            old_name="api_upload",
            new_name="hidden",
        ),
    ]
