# Generated by Django 5.2 on 2025-04-10 06:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("custom_images", "0004_rename_api_upload_customimage_hidden"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customimage",
            old_name="hidden",
            new_name="public",
        ),
    ]
