# Generated by Django 5.2.6 on 2025-10-21 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_images', '0006_remove_customimage_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='customimage',
            name='uploaded_text',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
