# Generated by Django 5.2.6 on 2025-10-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custom_images", "0007_customimage_uploaded_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="customimage",
            name="uploaded_user_name",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
    ]
