# Generated by Django 5.2 on 2025-05-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("experience", "0002_welcome_site_name_characteroverview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="welcome",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
