# Generated by Django 5.2 on 2025-05-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("experience", "0005_photographyscreen_yourcollection_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="introsearchandcollect",
            name="header",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
