# Generated by Django 5.2 on 2025-05-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("experience", "0006_introsearchandcollect_header"),
    ]

    operations = [
        migrations.RenameField(
            model_name="introsearchandcollect",
            old_name="header",
            new_name="heading",
        ),
        migrations.AddField(
            model_name="characteroverview",
            name="heading",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="photographyscreen",
            name="heading",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="yourcollection",
            name="heading",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
