# Generated by Django 5.2 on 2025-05-07 10:53

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("experience", "0007_rename_header_introsearchandcollect_heading_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="introsearchandcollect",
            name="description",
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
