# Generated by Django 5.2.1 on 2025-05-12 07:38

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0009_remove_yourcollection_image_description_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographyscreen',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
