# Generated by Django 5.2.1 on 2025-08-21 12:42

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0011_characteroverview_background_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteroverview',
            name='onboarding',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
