# Generated by Django 5.2.6 on 2025-10-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("experience", "0015_exploration_character_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallery",
            name="exit_button_text",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
