# Generated by Django 5.2.6 on 2025-10-17 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("experience", "0017_characters_character"),
        ("wagtailcore", "0095_groupsitepermission"),
    ]

    operations = [
        migrations.RenameField(
            model_name="character",
            old_name="default_collection",
            new_name="not_approved_collection",
        ),
        migrations.AddField(
            model_name="character",
            name="approved_collection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.collection",
            ),
        ),
    ]
