# Generated by Django 5.2.6 on 2025-10-20 11:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "experience",
            "0018_rename_default_collection_character_approved_collection_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="choosecharacter",
            options={
                "permissions": [
                    (
                        "choose_character.edit_restricted",
                        "Can edit restricted fields - Choose Character page",
                    )
                ]
            },
        ),
        migrations.AlterModelOptions(
            name="exploration",
            options={
                "permissions": [
                    (
                        "exploration.edit_restricted",
                        "Can edit restricted fields - Exploration page",
                    )
                ]
            },
        ),
    ]
