# Generated by Django 5.2.6 on 2025-10-22 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0019_alter_choosecharacter_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characteroverview',
            name='characters_image',
        ),
    ]
