# Generated by Django 5.2.6 on 2025-10-24 12:22

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("experience", "0021_remove_photo_gallery_button_text_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="choosecharacter",
            name="description",
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
