# Generated by Django 5.2.6 on 2025-10-27 08:39

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("experience", "0022_alter_choosecharacter_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagedescription",
            name="description",
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
