# Generated by Django 5.2.6 on 2025-10-27 09:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("experience", "0023_alter_imagedescription_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reflection",
            old_name="description",
            new_name="reflection_text",
        ),
        migrations.RemoveField(
            model_name="reflection",
            name="heading",
        ),
    ]
