# Generated by Django 5.2.6 on 2025-10-28 08:09

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0027_introduction_background_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choosecharacter',
            options={'permissions': [('choose_character.edit_restricted', 'Can edit restricted fields - Choose Character page')]},
        ),
        migrations.AlterModelOptions(
            name='introduction',
            options={'permissions': [('introduction.edit_restricted', 'Can edit restricted fields - Introduction page')]},
        ),
        migrations.RemoveField(
            model_name='experiencecreate',
            name='close_button_text',
        ),
        migrations.RemoveField(
            model_name='experiencecreate',
            name='exit_button_text',
        ),
        migrations.RemoveField(
            model_name='logbookrecord',
            name='record_button_text',
        ),
        migrations.RemoveField(
            model_name='logbookrecord',
            name='stop_button_text',
        ),
        migrations.AddField(
            model_name='experiencecreate',
            name='add_text_prompt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='logbookrecord',
            name='image_comment',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='continue_button_text',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='reflection',
            name='return_to_monument_button_text',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
