# Generated by Django 5.2.6 on 2025-10-28 08:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("experience", "0028_alter_choosecharacter_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="experiencegallery",
            name="no_button_text",
        ),
        migrations.RemoveField(
            model_name="experiencegallery",
            name="yes_button_text",
        ),
    ]
