# Generated by Django 5.2.6 on 2025-10-28 11:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("experience", "0029_remove_experiencegallery_no_button_text_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="logbookrecord",
            name="image_comment",
        ),
    ]
