# Generated by Django 5.2.8 on 2025-11-14 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0031_welcomelanguage_welcomeintro_language'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagedescription',
            options={},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={},
        ),
        migrations.AddField(
            model_name='imagedescription',
            name='locale',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale'),
        ),
        migrations.AddField(
            model_name='imagedescription',
            name='translation_key',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='locale',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale'),
        ),
        migrations.AddField(
            model_name='language',
            name='translation_key',
            field=models.UUIDField(editable=False, null=True),
        ),
    ]
