# Generated by Django 5.2.8 on 2025-11-14 13:08

from django.db import migrations
from wagtail.models import BootstrapTranslatableModel


class Migration(migrations.Migration):
    dependencies = [
        ("experience", "0032_alter_imagedescription_options_and_more"),
    ]

    operations = [
        BootstrapTranslatableModel("experience.Language"),
        BootstrapTranslatableModel("experience.ImageDescription"),
    ]
