# Generated by Django 5.2.10 on 2026-09-15 11:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("experience", "0035_chooseoption_option"),
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Reflection",
            new_name="Ending",
        ),
    ]
