# Generated by Django 5.2.10 on 2026-09-15 11:08

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models

import experience.child_capacity


class Migration(migrations.Migration):
    dependencies = [
        ("experience", "0036_rename_reflection_ending"),
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Survey",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("heading", models.CharField(blank=True, max_length=255, null=True)),
                ("description", wagtail.fields.RichTextField(blank=True, null=True)),
                ("survey_url", models.URLField(blank=True, null=True)),
                (
                    "survey_button_text",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "return_to_monument_button_text",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(experience.child_capacity.ChildCapacityMixin, "wagtailcore.page"),
        ),
        migrations.RenameField(
            model_name="ending",
            old_name="reflection_text",
            new_name="text",
        ),
        migrations.AddField(
            model_name="ending",
            name="continue_button_text",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
