# Generated by Django 5.2.10 on 2026-09-15 12:26

import django.db.models.deletion
import experience.child_capacity
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0037_survey_rename_reflection_text_ending_text_and_more'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowLink',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=(experience.child_capacity.ChildCapacityMixin, 'wagtailcore.page'),
        ),
    ]
