# Generated by Django 5.2 on 2025-04-03 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='description',
        ),
    ]
