# Generated by Django 5.2 on 2025-04-04 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custom_images", "0001_initial"),
        ("home", "0002_remove_home_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="home",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="custom_images.customimage",
            ),
        ),
    ]
